version: '3.9'

services:
  bot:
    container_name: ivl_usacli_bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - ./:/application
