name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed


jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull docker image
      run: sudo docker pull robertoguglielmin/ivl-usacli-bot:latest

    - name: Delete old docker container
      run: sudo docker rm -f ivl-usacli-bot-container || true

    - name: Run docker container
      run: sudo docker run -d -p 3000:3000 --name ivl-usacli-bot-container -e BOT_TOKEN=${{secrets.BOT_TOKEN}} robertoguglielmin/ivl-usacli-bot
